# Generated by Django 4.1.1 on 2022-09-13 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pack',
            options={'ordering': ['-added']},
        ),
    ]
