# Generated by Django 4.1.1 on 2022-09-13 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pack_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pack',
            options={'ordering': ['pack_name']},
        ),
    ]
