# Generated by Django 4.1.1 on 2022-09-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_mini_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mini',
            name='size',
            field=models.CharField(choices=[('N', 'None'), ('T', 'Tiny'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('H', 'Huge'), ('G', 'Gargantuan'), ('C', 'Colossal')], default='N', max_length=1),
        ),
    ]
